# Data Cleaning

In [4]:
import pandas as pd

In [93]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [24]:
'''
Null Values
----------
NaN -> Not a Number -> Object, Int, Float, Boolean
NaT -> Not a Time -> Date / Time
'''

'\nNull Values\n----------\nNaN -> Not a Number -> Object, Int, Float, Boolean\nNaT -> Not a Time -> Date / Time\n'

In [ ]:
'''
Process of Data Cleaning
---------------------------
1. Handle Null Value
    - Fill Null Values
        -> fillna()

        - Continuous Data -> Mean / Median
        -> Skewness -> .skew()
            -> 0 to 0.5 (Normal Distribution / Bell Curve) -> Mean
            -> Less than 0 (Left Skewness / Negative Skewness) or more than 0.5 (Right Skewness / Positive Skewness) -> Median

            -> Calculate both mean and median of data
            -> If both values are equal or almost equal -> Mean value

        -> Fill custom record if any values are not correct to fill.
        
        - Categorical Data / Discrete Data -> Mode
        
    - Drop Null Values
        -> dropna()
        -> If data consists of more than 70% null values drop column.

2. Remove Duplicate Records
    - Find duplicate records -> duplicated()
    - Remove duplicate records -> drop_duplicates()

3. Remove Unwanted Data
    a. Remove unwanted characters
        -> str.replace()
    b. Remove Whitespace
        -> str.strip()
    c. Text Transformation
        -> str.upper() / str.lower() / str.capitalize()
'''

## Drop Null Values

In [94]:
# information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [108]:
# To check null values
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [ ]:
# dropna()
'''
To change data permanently
------------------------------
1. inplace = True / False (default)

Dropna Arguments
----------------
1. inplace = True / False
2. axis = 0 (Row) (default) / 1 (Column)
3. how = any (default) / all
'''
# df.dropna(axis=1, how='any', inplace=True)

# df.drop(index=0) -> to remove row
# df.drop(columns=['SALARY', 'EMAIL']) -> to remove columns

In [43]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

## Fill Data

In [96]:
commission_skew = df['COMMISSION_PCT'].skew()
commission_skew

np.float64(0.09661736135041571)

In [97]:
commission_mean = round(df['COMMISSION_PCT'].mean(), 2)
commission_median = df['COMMISSION_PCT'].median()

print(f'Commission Mean: {commission_mean}')
print(f'Commission Median: {commission_median}')

Commission Mean: 0.22
Commission Median: 0.2

In [98]:
# df['COMMISSION_PCT'].fillna(commission_mean, inplace=True)
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(commission_mean)
df.fillna({'COMMISSION_PCT': commission_mean}, inplace=True)

In [99]:
# df['COMMISSION_PCT'].unique()

In [100]:
## Fill Manager Record

In [105]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [106]:
print(mgr_mode)
print(dep_mode)

100.0
50.0

In [107]:
df.fillna({'MANAGER_ID': mgr_mode}, inplace=True)
df.fillna({'DEPARTMENT_ID': dep_mode}, inplace=True)

### Fraud Dataset

In [36]:
fraud = pd.read_csv('Dataset/Fraud Detection Dataset.csv')
fraud.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [37]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  object
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  object
 4   Time_of_Transaction               48448 non-null  float64
 5   Device_Used                       48527 non-null  object
 6   Location                          48453 non-null  object
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    48531 non-null  object
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.7+ MB

In [44]:
fraud.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                 2500
Device_Used                         2433
Location                            2500
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2422
Fraudulent                             0
dtype: int64

#### Duplicate Data

In [39]:
## Find duplicate values
# duplicated(subset = [column_name])
# drop_duplicated(subset = [column_name], keep='first'/'last')
duplicate_data = fraud[fraud.duplicated(subset=['Transaction_ID'])]
# duplicate_data

In [40]:
fraud = fraud.drop_duplicates(subset=['Transaction_ID'])

#### Clean Data

In [41]:
fraud['Transaction_Amount'].skew()

np.float64(8.441724020803951)

In [24]:
median_amount = fraud['Transaction_Amount'].median()
fraud.fillna({'Transaction_Amount': median_amount}, inplace=True)

In [26]:
time_mode = fraud['Time_of_Transaction'].mode()[0]
fraud.fillna({'Time_of_Transaction': time_mode}, inplace=True)

In [47]:
fraud['Device_Used'].unique()

array(['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device'], dtype=object)

In [48]:
fraud.fillna({'Device_Used': 'Unknown Device'}, inplace=True)

In [49]:
fraud['Location'].unique()

array(['San Francisco', 'New York', nan, 'Chicago', 'Boston', 'Houston',
       'Miami', 'Los Angeles', 'Seattle'], dtype=object)

In [50]:
fraud.fillna({'Location': 'Unknown Location'}, inplace=True)

In [51]:
fraud['Payment_Method'].unique()

array(['Debit Card', 'Credit Card', nan, 'UPI', 'Net Banking',
       'Invalid Method'], dtype=object)

In [52]:
fraud.fillna({'Payment_Method': 'Unknown Method'}, inplace=True)

In [35]:
# function to clean data
def clean_data(dataframe, column, data):
    dataframe.fillna({column:data}, inplace=True)

In [45]:
median_amount = fraud['Transaction_Amount'].median()
time_mode = fraud['Time_of_Transaction'].mode()[0]
# fraud.fillna({'Transaction_Amount': median_amount}, inplace=True)

In [43]:
clean_data(fraud, 'Transaction_Amount', median_amount)

In [46]:
clean_data(fraud, 'Time_of_Transaction', time_mode)

## Remove Unwanted Data

In [5]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [6]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [7]:
hr.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

#### Clean Data

In [8]:
mgr_mode = hr['ManagerID'].mode()[0]
hr.fillna({'ManagerID': mgr_mode}, inplace=True)

#### Duplicate Data

In [9]:
duplicate_data = hr[hr.duplicated(subset=['EmpID'])]
# duplicate_data.head()

In [9]:
# check specific duplicate values
# emp_id = int(input('Enter employee id: '))
# data = hr[hr['EmpID'] == emp_id]
# data

In [10]:
hr = hr.drop_duplicates(subset=['EmpID'])
# hr

In [11]:
# select_dtypes() -> select specific data types data.
# object_data = hr.select_dtypes(['object', 'int64'])
object_data = hr.select_dtypes(['object'])
object_data.columns

Index(['Employee_Name', 'Position', 'State', 'DOB', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'LastPerformanceReview_Date'],
      dtype='object')

In [12]:
# remove unwanted column
object_data = object_data.drop(columns=['DateofTermination', 'DOB', 'DateofHire', 'LastPerformanceReview_Date'])

In [13]:
object_data.columns

Index(['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore'],
      dtype='object')

In [14]:
# object_data['Department'].unique()

In [15]:
## Function to find unique values
columns = ['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']

def unique_values(dataframe, data_columns):
    for col in data_columns:
        print(col)
        print('-'*35)
        unique_data = dataframe[col].unique()
        print(unique_data)
        print('\n')

In [16]:
# unique_values(object_data, columns)

#### Strip Data

In [17]:
object_data['Department'] = object_data['Department'].str.strip()

In [18]:
def removeWhiteSpace(dataframe, data_columns):
    for col in data_columns:
        dataframe[col] = dataframe[col].str.strip()

In [19]:
removeWhiteSpace(hr, columns)

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\1672276647.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[col] = dataframe[col].str.strip()

#### Replace Data

In [20]:
'''
-> .str.replace()
Special Characters / regular expressions -> .str.replace(find, replace_value, regex=False/True (default))
Normal Text -> str.replace(find, replace_value)
'''

'\n-> .str.replace()\nSpecial Characters / regular expressions -> .str.replace(find, replace_value, regex=False/True (default))\nNormal Text -> str.replace(find, replace_value)\n'

In [21]:
hr['Employee_Name'] = hr['Employee_Name'].str.replace(',', ' ', regex=False)

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\2864162168.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hr['Employee_Name'] = hr['Employee_Name'].str.replace(',', ' ', regex=False)

In [22]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
326,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
327,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
328,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
329,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

In [23]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 89.9+ KB

In [24]:
# import re
# text = '##  @ abcd %% &'
# data = re.sub(r'[^A-Za-z0-9]', '', text)
# data

#### Change DataType

In [25]:
# .astype(datatype) -> int, float, boolean, object/str
hr['ManagerID'] = hr['ManagerID'].astype(int)

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\1145444697.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hr['ManagerID'] = hr['ManagerID'].astype(int)

In [26]:
## DateTime
'''
Format
--------
1. '%d.%m.%y'
2. '%d-%m-%y'
3. mixed

dayfirst=True/False (default)
'''

"\nFormat\n--------\n1. '%d.%m.%y'\n2. '%d-%m-%y'\n3. mixed\n\ndayfirst=True/False (default)\n"

In [27]:
# ['DateofTermination', 'DOB', 'DateofHire', 'LastPerformanceReview_Date']
# dataframe[col] = pd.to_datetime(dataframe[col], format='mixed'/dayfirst=True)
# After Conversion -> YYYY-MM-DD
hr['DOB'] = pd.to_datetime(hr['DOB'], format='mixed')

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\2430168775.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hr['DOB'] = pd.to_datetime(hr['DOB'], format='mixed')

In [28]:
def changeDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [29]:
changeDateTime(hr, 'DateofTermination', 'DOB', 'DateofHire', 'LastPerformanceReview_Date')

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\3708269836.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')
C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\3708269836.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')
C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\3708269836.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')
C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\3708269836.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [30]:
hr.to_csv('hr_cleaned_data.csv', index=False)
hr.to_excel('hr_cleaned_data.xlsx', index=False)
hr.to_json('hr_cleaned_data.json', indent=4)

In [31]:
hr['HispanicLatino'].unique()

array(['No', 'Yes', 'no', 'yes'], dtype=object)

In [32]:
hr['HispanicLatino'] = hr['HispanicLatino'].str.capitalize()

C:\Users\Asus\AppData\Local\Temp\ipykernel_32648\2505350136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hr['HispanicLatino'] = hr['HispanicLatino'].str.capitalize()

In [33]:
hr_csv = pd.read_csv('hr_cleaned_data.csv')

In [34]:
# hr_csv.info()

In [35]:
hr_excel = pd.read_excel('hr_cleaned_data.xlsx')

In [36]:
# hr_excel.info()

In [37]:
hr_json = pd.read_json('hr_cleaned_data.json')
hr_json.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    int64
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    int64
 22  DateofTermination           104 non-null    float64
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    int64
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(20), object(14)
memory usage: 89.9+ KB