# Data Cleaning

In [1]:
import pandas as pd

In [93]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [24]:
'''
Null Values
----------
NaN -> Not a Number -> Object, Int, Float, Boolean
NaT -> Not a Time -> Date / Time
'''

'\nNull Values\n----------\nNaN -> Not a Number -> Object, Int, Float, Boolean\nNaT -> Not a Time -> Date / Time\n'

In [ ]:
'''
Process of Data Cleaning
---------------------------
1. Handle Null Value
    - Fill Null Values
        -> fillna()

        - Continuous Data -> Mean / Median
        -> Skewness -> .skew()
            -> 0 to 0.5 (Normal Distribution / Bell Curve) -> Mean
            -> Less than 0 (Left Skewness / Negative Skewness) or more than 0.5 (Right Skewness / Positive Skewness) -> Median

            -> Calculate both mean and median of data
            -> If both values are equal or almost equal -> Mean value

        -> Fill custom record if any values are not correct to fill.
        
        - Categorical Data / Discrete Data -> Mode
        
    - Drop Null Values
        -> dropna()
        -> If data consists of more than 70% null values drop column.

2. Remove Duplicate Records
    - Find duplicate records -> duplicated()
    - Remove duplicate records -> drop_duplicates()

3. Remove Unwanted Data
    a. Remove unwanted characters
        -> str.replace()
    b. Remove Whitespace
        -> str.strip()
    c. Text Transformation
        -> str.upper() / str.lower() / str.capitalize()
'''

## Drop Null Values

In [94]:
# information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [108]:
# To check null values
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [ ]:
# dropna()
'''
To change data permanently
------------------------------
1. inplace = True / False (default)

Dropna Arguments
----------------
1. inplace = True / False
2. axis = 0 (Row) (default) / 1 (Column)
3. how = any (default) / all
'''
# df.dropna(axis=1, how='any', inplace=True)

# df.drop(index=0) -> to remove row
# df.drop(columns=['SALARY', 'EMAIL']) -> to remove columns

In [43]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

## Fill Data

In [96]:
commission_skew = df['COMMISSION_PCT'].skew()
commission_skew

np.float64(0.09661736135041571)

In [97]:
commission_mean = round(df['COMMISSION_PCT'].mean(), 2)
commission_median = df['COMMISSION_PCT'].median()

print(f'Commission Mean: {commission_mean}')
print(f'Commission Median: {commission_median}')

Commission Mean: 0.22
Commission Median: 0.2

In [98]:
# df['COMMISSION_PCT'].fillna(commission_mean, inplace=True)
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(commission_mean)
df.fillna({'COMMISSION_PCT': commission_mean}, inplace=True)

In [99]:
# df['COMMISSION_PCT'].unique()

In [100]:
## Fill Manager Record

In [105]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [106]:
print(mgr_mode)
print(dep_mode)

100.0
50.0

In [107]:
df.fillna({'MANAGER_ID': mgr_mode}, inplace=True)
df.fillna({'DEPARTMENT_ID': dep_mode}, inplace=True)