In [ ]:
'''
- Used for Data cleaning, feature engineering, data analysis
'''

# Pandas

In [1]:
import pandas as pd

In [2]:
# 1D -> Series
# 2D -> DataFrame

## Series

In [9]:
alphabets = pd.Series(['A', 'B', 'C', 'D', 'E', 'F'], index=['aa', 'bb', 'cc', 'dd', 'ee', 'ff'])
alphabets

aa    A
bb    B
cc    C
dd    D
ee    E
ff    F
dtype: object

In [ ]:
'''
Alias for Index
--------------
for column:
Columns = ['name1', 'name2', 'name3', ..., 'name_n']

for row:
index = ['name1', 'name2', 'name3', ..., 'name_n']
'''

In [12]:
products = pd.DataFrame([
    ['Watch', 'NavyForce', 2018, 'Rs.35000'],
    ['TV', 'MI', 2022, 'Rs.45000'],
    ['Laptop', 'HP', 2024, 'Rs.150000'],
    ['Mobile', 'Samsung', 2024, 'Rs.150000']
], columns = ['Product Name', 'Brand', 'Model Year', 'Price'],
    index=['A', 'B', 'C', 'D'])
products

  Product Name      Brand  Model Year      Price
A        Watch  NavyForce        2018   Rs.35000
B           TV         MI        2022   Rs.45000
C       Laptop         HP        2024  Rs.150000
D       Mobile    Samsung        2024  Rs.150000

In [11]:
alphabets[0:3]

aa    A
bb    B
cc    C
dtype: object

## Slicing

### Loc and ILoc

In [ ]:
'''
Loc -> Location
ILoc -> Integer Location
'''

In [23]:
products.iloc[1:, 1:3]

     Brand  Model Year
B       MI        2022
C       HP        2024
D  Samsung        2024

In [21]:
products.loc['B':'D', 'Brand':'Model Year']

     Brand  Model Year
B       MI        2022
C       HP        2024
D  Samsung        2024

In [25]:
products.loc[
    ['A', 'D'],
    ['Product Name', 'Price']
]

  Product Name      Price
A        Watch   Rs.35000
D       Mobile  Rs.150000

In [26]:
products.iloc[
    [0, 3],
    [0, 3]
]

  Product Name      Price
A        Watch   Rs.35000
D       Mobile  Rs.150000

In [28]:
products.iloc[:,0]

A     Watch
B        TV
C    Laptop
D    Mobile
Name: Product Name, dtype: object

In [29]:
# information -> info()

products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  4 non-null      object
 1   Brand         4 non-null      object
 2   Model Year    4 non-null      int64
 3   Price         4 non-null      object
dtypes: int64(1), object(3)
memory usage: 332.0+ bytes

In [30]:
products.shape

(4, 4)

In [31]:
products.size

16

In [32]:
products.ndim

2

## Read Data

In [ ]:
'''
CSV -> read_csv()
Excel -> read_excel()
JSON -> read_json()
SQL -> read_sql()
'''

In [33]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [40]:
# top 5 record
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [42]:
# bottom 5 record
df.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0